import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import { MantineProvider, ColorSchemeScript } from '@mantine/core';
import '@mantine/core/styles.css';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <head>
                <ColorSchemeScript />
            </head>
            <body className={montserrat.className}>
                <MantineProvider>{children}</MantineProvider>
            </body>
        </html>
    );
}
